#!/usr/bin/perl

# From p. 69


sub print_nums {
    my($num_1) = @_;
    my $num_2 = @_;
    my($num_3) = (100, 200, 300);
    my $num_4 = (100, 200, 300);

    print "$num_1\n";
    print "$num_2\n";
    print "$num_3\n";
    print "$num_4\n";
}

print_nums 10, 20, 30;

